- Rofl.Files/Repositories/DatabaseRepository.cs
- Rofl.UI.Main/Rofl.UI.Main.csproj
- Rofl.UI.Main/ViewModels/MainWindowViewModel.cs
- Rofl.UI.Main/Views/MainWindow.xaml.cs
- Rofl.UI.Main/packages.config
* [Fix] LiteDB was not being included in the main project, causing Rofl.Files to crash
* [Enhancement] Added more logging to better catch problems
> Pre-Release 5 Hotfix

- Rofl.UI.Main/Resources/Strings.xaml
- Rofl.UI.Main/Utilities/FileAssociations.cs
- Rofl.UI.Main/Views/SettingsWindow.xaml.cs
- Delete existing .rofl keys so our new value is used
- Add dialog for file association button
> Another fix for the file association button

- Rofl.UI.Main/Controls/StatisticsControl.xaml
- Rofl.UI.Main/Views/ExportReplayDataWindow.xaml
- Rofl.UI.Main/Views/MainWindow.xaml
- Rofl.UI.Main/Views/WelcomeSetupWindow.xaml
- Change welcome setup background from pure black
- Add vertical line between list and detail
- Change export window background to darker color
- Tooltips added for all stats headers
> Style updates

- Rofl.UI.Main/Resources/Strings_zh_cn.xaml
> Simplified Chinese Language Pack

- .github/workflows/build.yml
- .gitignore
- Rofl.Requests/Models/RuneRequest.cs
- Rofl.Requests/RequestManager.cs
- Rofl.Requests/Utilities/CacheClient.cs
- Rofl.Requests/Utilities/DownloadClient.cs
- Rofl.UI.Main/App.xaml.cs
- Rofl.UI.Main/Controls/PlayerRunesControl.xaml
- Rofl.UI.Main/Controls/PlayerRunesControl.xaml.cs
- Rofl.UI.Main/Controls/ReplayDetailControl.xaml
- Rofl.UI.Main/Controls/ReplayDetailControl.xaml.cs
- Rofl.UI.Main/Controls/RuneIconControl.xaml
- Rofl.UI.Main/Controls/RuneIconControl.xaml.cs
- Rofl.UI.Main/Controls/RunesDetailControl.xaml
- Rofl.UI.Main/Controls/RunesDetailControl.xaml.cs
- Rofl.UI.Main/Controls/StatisticsControl.xaml
- Rofl.UI.Main/Models/PlayerDetail.cs
- Rofl.UI.Main/Models/Rune.cs
- Rofl.UI.Main/Pages/WelcomeSetupDownload.xaml
- Rofl.UI.Main/Pages/WelcomeSetupDownload.xaml.cs
- Rofl.UI.Main/Resources/Strings/en.xaml
- Rofl.UI.Main/Rofl.UI.Main.csproj
- Rofl.UI.Main/Utilities/RuneHelper.cs
- Rofl.UI.Main/ViewModels/MainWindowViewModel.cs
- Rofl.UI.Main/Views/MainWindow.xaml.cs
- Rofl.UI.Main/Views/SettingsWindow.xaml
- Rofl.UI.Main/Views/SettingsWindow.xaml.cs
- scripts/generate-runes.py
- added rune layout in detail view
- included rune packaging script and workflow tasks
- Misc fixes
> Display runes

- Rofl.UI.Main/Resources/Strings/zh-Hans.xaml
> Update simplified Chinese translation

- Rofl.UI.Main/Resources/Strings/es.xaml
Hi! I downloaded your (really neat) tool and noticed it was missing a language. Here's my go at it. I've cross referenced official League translations for the stats page and done my best to keep the translation short and effective. I don't have the resources or knowledge to test it in the actual app, so if any changes are to be made, you let me know.
> Spanish translation

- Rofl.UI.Main/Resources/Strings/es.xaml
Since the translation is now properly being looked into, I took the liberty to proofread my own work from two days ago. There were two lines that had some leftover garbage - I've properly disposed of that in this commit. Please check and advise, and as always, let me know if you need anything else.
I joined your Discord server, you can find me there. Exact same username and everything.
> further proofreading

- Rofl.Settings/Models/GeneralSettings.cs
- Rofl.Settings/Models/ObservableSettings.cs
- Rofl.Settings/Models/SettingsModel.cs
- Rofl.Settings/SettingsManager.cs
- Rofl.UI.Main/Controls/ReplayDetailControl.xaml
- Rofl.UI.Main/Controls/ReplayDetailControl.xaml.cs
- Rofl.UI.Main/Controls/ReplayItemControl.xaml
- Rofl.UI.Main/Controls/ReplayItemControl.xaml.cs
- Rofl.UI.Main/Resources/Strings/de.xaml
- Rofl.UI.Main/Resources/Strings/en.xaml
- Rofl.UI.Main/Resources/Strings/es.xaml
- Rofl.UI.Main/Resources/Strings/zh-Hans.xaml
- Rofl.UI.Main/ViewModels/MainWindowViewModel.cs
- Rofl.UI.Main/Views/ExecutableDetailDialog.xaml
- Rofl.UI.Main/Views/ExecutableLaunchArgsWindow.xaml
- Rofl.UI.Main/Views/ExportReplayDataWindow.xaml
- Rofl.UI.Main/Views/MainWindow.xaml
- Rofl.UI.Main/Views/MainWindow.xaml.cs
- Rofl.UI.Main/Views/PlayerMarkerDialog.xaml
- Rofl.UI.Main/Views/SettingsWindow.xaml
- Rofl.UI.Main/Views/SettingsWindow.xaml.cs
- Rofl.UI.Main/Views/WelcomeSetupWindow.xaml
fix status bar disappearing/redundant message
no longer hangs when searching for executables
view online feature removed
> Various fixes

- Rofl.UI.Main/Views/SettingsWindow.xaml.cs
> disable button when pressed

- Rofl.UI.Main/Resources/Strings/zh-Hans.xaml
Added some string translations that had not been translated before
> Update simplified Chinese translation.

- src/Rofl.Executables.Old/Utilities/LeagueExecutableExtensions.cs
- src/Rofl.Files/Repositories/DatabaseRepository.cs
- src/Rofl.Requests/RequestManager.cs
- src/Rofl.UI.Main/Controls/ReplayItemControl.xaml
- src/Rofl.UI.Main/Controls/ScoreboardControl.xaml
- src/Rofl.UI.Main/ViewModels/MainWindowViewModel.cs
- src/Rofl.UI.Main/Views/ExecutableDetailDialog.xaml.cs
- src/Rofl.UI.Main/Views/PlayerMarkerDialog.xaml.cs
fixes #141 
fixes #139 
resolves warning messages
> Fix bugs related to .NET 6 migration

- .github/workflows/build.yml
- .github/workflows/release.yml
- .gitignore
- src/Rofl.Requests/RequestManager.cs
- src/Rofl.UI.Main/App.xaml.cs
- src/Rofl.UI.Main/Controls/ItemIconControl.xaml
- src/Rofl.UI.Main/Controls/PlayerIconControl.xaml
- src/Rofl.UI.Main/Models/Item.cs
- src/Rofl.UI.Main/Models/PlayerPreview.cs
- src/Rofl.UI.Main/Pages/WelcomeSetupDownload.xaml
- src/Rofl.UI.Main/Pages/WelcomeSetupDownload.xaml.cs
- src/Rofl.UI.Main/Utilities/ChampionHelper.cs
- src/Rofl.UI.Main/Utilities/ItemHelper.cs
- src/Rofl.UI.Main/Utilities/LanguageHelper.cs
- src/Rofl.UI.Main/Utilities/ResourceTools.cs
- src/Rofl.UI.Main/ViewModels/MainWindowViewModel.cs
- src/Rofl.UI.Main/Views/MainWindow.xaml.cs
- src/Rofl.UI.Main/Views/SettingsWindow.xaml
- src/Rofl.UI.Main/Views/SettingsWindow.xaml.cs
- src/Rofl.UI.Main/Views/SingleReplayWindow.xaml.cs
- src/scripts/generate-champions.py
- src/scripts/generate-items.py
Instead of downloading individual images, use sprite sheets provided by riot.
> Better image loading

- src/Rofl.UI.Main/Pages/ExportWizardAttributes.xaml.cs
> Fix deselect menu option is exporter, attributes list

- src/Fraxiinus.ReplayBook.Configuration/Models/StaticConfigurationDefinitions.cs
- src/Fraxiinus.ReplayBook.UI.Main/Pages/WelcomeSetupIntroduction.xaml
- src/Fraxiinus.ReplayBook.UI.Main/Pages/WelcomeSetupIntroduction.xaml.cs
- src/Fraxiinus.ReplayBook.UI.Main/Resources/Acknowledgements.xaml
- src/Fraxiinus.ReplayBook.UI.Main/Resources/Strings/zh-Hant.xaml
- src/Fraxiinus.ReplayBook.UI.Main/Utilities/LanguageHelper.cs
- src/Fraxiinus.ReplayBook.UI.Main/Views/SettingsWindow.xaml.cs
- src/Fraxiinus.ReplayBook.UI.Main/Views/WelcomeSetupWindow.xaml
- src/Fraxiinus.ReplayBook.UI.Main/Views/WelcomeSetupWindow.xaml.cs
- src/scripts/generate-champions.py
- src/scripts/generate-items.py
- src/scripts/generate-runes.py
- add traditional chinese
- language lookup optimization
- sort languages by name
> language updates

- src/UI.Main/Resources/Strings/zh-Hans.xaml
- src/UI.Main/Resources/Strings/zh-Hant.xaml
Translations of Simplified and Traditional Chinese of Key "ErdPresetInvalidNotify" are added.
> Update Simplified/Traditional Chinese translation

- src/StaticData/Data/CommunityDragonClient.cs
- src/StaticData/Data/DataDragonClient.cs
- src/UI.Main/Controls/ReplayItemControl.xaml.cs
- src/UI.Main/Pages/WelcomeSetupDownload.xaml
- src/UI.Main/Pages/WelcomeSetupDownload.xaml.cs
- src/UI.Main/Pages/WelcomeSetupFinish.xaml.cs
- src/UI.Main/Resources/Strings/en.xaml
- src/UI.Main/UI.Main.csproj
- src/UI.Main/Views/SettingsWindow.xaml.cs
- src/UI.Main/Views/StaticDataAddDialog.xaml
- src/UI.Main/Views/StaticDataAddDialog.xaml.cs
- src/UI.Main/Views/StaticDataDownloadDialog.xaml.cs
- src/UI.Main/Views/StaticDataRetryDialog.xaml
- src/UI.Main/Views/StaticDataRetryDialog.xaml.cs
> Consolidate static data downloads into dialog

- src/UI.Main/Views/StaticDataDownloadDialog.xaml.cs
> always save bundle information after download

- .gitignore
- src/UI.Main/Resources/Strings/en.xaml
- src/UI.Main/Views/SingleReplayWindow.xaml.cs
> fix error handling, show fancy new error dialog

- src/UI.Main/Pages/WelcomeSetupFinish.xaml.cs
> fix welcome setup finish crash

- src/UI.Main/Pages/WelcomeSetupDownload.xaml.cs
> use second most recent patch by default

- src/UI.Main/Resources/Acknowledgements.xaml
> remove newtonsoftjson

- src/UI.Main/Views/StaticDataDownloadDialog.xaml.cs
> Fix matching version substring

- src/UI.Main/Models/ExportAttributeSelectItem.cs
- src/UI.Main/Models/ExportDataContext.cs
- src/UI.Main/Pages/ExportWizardAdvanced.xaml
- src/UI.Main/Pages/ExportWizardAdvanced.xaml.cs
- src/UI.Main/Pages/ExportWizardAttributes.xaml.cs
- src/UI.Main/Pages/ExportWizardFinish.xaml
- src/UI.Main/Pages/ExportWizardFinish.xaml.cs
- src/UI.Main/Pages/ExportWizardLanding.xaml.cs
- src/UI.Main/Resources/Strings/en.xaml
- src/UI.Main/Utilities/ExportHelper.cs
- src/UI.Main/ViewModels/MainWindowViewModel.cs
- src/UI.Main/Views/ExportDataWindow.xaml.cs
> static data in exporter

- src/StaticData/Data/CommunityDragonClient.cs
- src/StaticData/Data/DataDragonClient.cs
- src/StaticData/Models/ObservableStaticDataContext.cs
- src/StaticData/StaticDataManager.cs
- src/UI.Main/Resources/Strings/en.xaml
- src/UI.Main/Views/StaticDataDownloadDialog.xaml.cs
- src/UI.Main/Views/StaticDataRetryDialog.xaml
- src/UI.Main/Views/StaticDataRetryDialog.xaml.cs
Culture related bugs and empty directory crash
> Static Data Bugs

- src/UI.Main/Resources/Strings/ru.xaml
~95% of the stats translations was taken from the league file ((obsidian)/plugins/rcp-fe-lol-match-history/global/ru_ru/trans.json)
> ru translation

- src/UI.Main/Resources/Strings/fr.xaml
Added missing French translation and fixed an invalid translation
> Added missing French translation
